---
apiVersion: v1
kind: Service
metadata:
  name: edge-service-expose
  namespace: default
  labels:
    app: edge-service
spec:
  ports:
  - name: edge-service
    protocol: TCP
    port: 31706
    targetPort: 9999
    nodePort: 31706
  selector:
    app: edge-service
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
---
apiVersion: v1
kind: Service
metadata:
  name: edge-service
  labels:
    app: edge-service
spec:
  ports:
  - port: 9999
    targetPort: 9999
    name: edge-service
  clusterIP: None
  selector:
    app: edge-service
---    
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: edge-service
spec:
  serviceName: "edge-service"
  replicas: 1
  selector:
    matchLabels:
      app: edge-service
  template:
    metadata:
      labels:
        app: edge-service
    spec:
      containers:
      - resources:
          requests:
            cpu: 100m
            memory: 192Mi 
        name: edge-service
        image: mycluster.icp:8500/default/kbastani/edge-service:latest
        ports:
        - containerPort: 9999
        env:
        - name: JAVA_OPTS
          value: |
            -Xmx160m
        - name: spring.profiles.active
          value: "cloud"
        - name: spring.cloud.config.uri
          value: "http://config-service.default.svc.cluster.local:8888"
  podManagementPolicy: "Parallel"
